# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: vittles ci

on:
  push:
    branches: [ "feature/add-ci" ]
  pull_request:
    branches: [ "feature/add-ci" ]

permissions:
  contents: read

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest
    container: ubuntu 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies for OS
        run: |
          apt-get update
          apt-get install -y build-essential
          ./ensure-texlive.sh
      - name: Create devenv
        run: make devenv
      - name: Run tests
        run: make test
      - name: Get coverage
        run: make coverage
  
  build-archlinux:

    runs-on: ubuntu-latest
    container: archlinux 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies for OS
        run: |
          pacman -Syu --noconfirm
          pacman -Syu --noconfirm base-devel
          ./ensure-texlive.sh
      - name: Create devenv
        run: make devenv
      - name: Run tests
        run: make test
      - name: Get coverage
        run: make coverage    
  
  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v1 # Or another Cygwin installer action
        with:
          packages: >
            bash
            coreutils
            perl
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4 # Or another TeX Live installer action
        with:
          packages: >
            lmodern
            textcomp
            lastpage
            lettrine
            cookingsymbols
            xcookybooky
      - name: Link for venv
        run: cmd.exe /c mklink /j "devenv/bin/activate" "devenv/Scripts/activate"
      - name: Create devenv
        run: make devenv
        shell: C:\cygwin64\bin\bash.exe --login '{0}'
      - name: Run tests
        run: make test
        shell: C:\cygwin64\bin\bash.exe --login '{0}'
      - name: Get coverage
        run: make coverage    
        shell: C:\cygwin64\bin\bash.exe --login '{0}'
  
  build-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies for OS
        run: ./ensure-texlive.sh
      - name: Create devenv
        run: make devenv
      - name: Run tests
        run: make test
      - name: Get coverage
        run: make coverage
